on:
  push:
    branches:
      - master
    









jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      -  uses: actions/checkout@v3


      -  name: "Login to Docker Hub"
         run: docker login --username ${{ secrets.USERNAMED }} --password ${{ secrets.TOKEN }}
      -  name: "Build image"
         run: docker build -t ${{ secrets.USERNAMED }}/newimage .
      -  name: "push Docker Hub"
         run: docker push ${{ secrets.USERNAMED }}/newimage

